### ISSUE TITLE
Запуск скрипту на MacOS

### ISSUE THREAD

**Issue by myr4ik07** [alexnest-ua/runner_for_windows#4]
При запуску на MacOS 12.3.1 (21E258)

отримую

bash-3.2$ bash setup.sh 
Cloning into 'mhddos_proxy'...
remote: Enumerating objects: 773, done.
remote: Counting objects: 100% (773/773), done.
remote: Compressing objects: 100% (523/523), done.
remote: Total 773 (delta 512), reused 480 (delta 243), pack-reused 0
Receiving objects: 100% (773/773), 223.02 KiB | 1.51 MiB/s, done.
Resolving deltas: 100% (512/512), done.
**setup.sh: line 5: python: command not found**

**Comment by alexnest-ua** [comment]
А хто сказав, що воно підтримується на MacOs? Я не можу поки що зробити норм версію під Mac, бо у мене його немає(

**Comment by myr4ik07** [comment]
> А хто сказав, що воно підтримується на MacOs? Я не можу поки що зробити норм версію під Mac, бо у мене його немає(

В телеграм чаті порекомендували спробувати - спробував, шкода не запустилось.

**Comment by myr4ik07** [comment]
> А хто сказав, що воно підтримується на MacOs? Я не можу поки що зробити норм версію під Mac, бо у мене його немає(

я можу надати віддалений доступ до свого пк, якщо потрібно, можете спробувати розробити на ньому таку версію, яка буде працювати для даної ОС.

**Comment by alexnest-ua** [comment]
напишіть мені в телеграм @brainqdead , але я не обіцяю, що швидко відповім)

**Comment by alexnest-ua** [comment]
@myr4ik07 напишіть ще раз, будь ласка, бо я вас загубив(

**Comment by alexnest-ua** [comment]
Зроблено: https://github.com/alexnest-ua/auto_mhddos_mac
