### ISSUE TITLE
Прошу добавити параметр

### ISSUE THREAD

**Issue by sserkez** [alexnest-ua/runner_for_windows#5]
Прошу добавити можливість передати параметр --itarmy в runner.py через runner.sh
можливо після [num_of_copies] [threads] [rpc] [debug] [vpn]
в іншому випадку як його замінити? 
Дякую

**Comment by alexnest-ua** [comment]
Ніяк, я можу активувати(розкоментувати(прибрати #)) тут `--itarmy`: https://github.com/alexnest-ua/targets/blob/main/targets_linux , але самі подумайте, чи є сенс, якщо там на каналі і так 250 000 підписників, і того з головою достатньо, щоб заДДоСити їх список цілей.

Насправді, якщо сайт реально лягає, то 1000 машин з головою буде достатньо, а якщо на сайті ДДоС-захист / геоблокування, то він і від 100 000 машин **не** ляже, на жаль.

Саме тому я залишив один список цілей: -c https://raw.githubusercontent.com/alexnest-ua/targets/main/special/archive/providers/providers_l7 де зараз налічується 1300+ різних цілей, а `num_of_copies` корегує кількість запущених копій. 

Не бачу сенсу віддавати невеликі потужності юзерів свого скрипта на IT Army, бо у них і так 250 000 підписників, а у мене лише 50  000 тут: https://t.me/ddos_separ
